name: Deploy GitHub Pages with Secret API Key

on:
  push:
    branches:
      - master  # Trigger the action on pushes to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the code from the repository

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'  # Specify the Ruby version

    - name: Install Bundler and dependencies
      run: |
        gem install bundler
        bundle install  # Install Ruby dependencies

    - name: Inject API Key
      run: |
        # Use 'sed' to replace the placeholder with the actual API key in your JavaScript file
        sed -i 's/LASTFM_API_KEY/${{ secrets.LASTFM_API_KEY }}/g' _pages/about.md

    - name: Build the site
      run: bundle exec jekyll build  # Build the Jekyll site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site  # This assumes you're using Jekyll; adjust if necessary